unstable_features = true
disable_all_formatting = false
edition = "2018"

condense_wildcard_suffixes = true
format_strings = true
hard_tabs = true
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
normalize_doc_attributes = true
